namespace TokenRateGate.Abstractions;

/// <summary>
/// Provides token estimation for LLM requests before they are sent to the provider.
/// Implementations should provide model-specific token counting logic.
/// </summary>
/// <typeparam name="TRequest">The type of request object for the LLM provider</typeparam>
public interface ITokenEstimator<in TRequest>
{
    /// <summary>
    /// Estimates the number of input tokens that will be consumed by the request.
    /// This should account for all parts of the request (messages, system prompts, function definitions, etc.)
    /// </summary>
    /// <param name="request">The request to estimate tokens for</param>
    /// <param name="cancellationToken">Cancellation token for the operation</param>
    /// <returns>The estimated number of input tokens</returns>
    /// <exception cref="ArgumentNullException">Thrown when request is null</exception>
    Task<int> EstimateInputTokensAsync(TRequest request, CancellationToken cancellationToken = default);

    /// <summary>
    /// Estimates the number of output tokens that will be generated by the response.
    /// This is inherently uncertain and may use strategies like fixed multipliers,
    /// max_tokens parameter values, or historical averages.
    /// </summary>
    /// <param name="request">The request to estimate output tokens for</param>
    /// <param name="cancellationToken">Cancellation token for the operation</param>
    /// <returns>The estimated number of output tokens</returns>
    /// <exception cref="ArgumentNullException">Thrown when request is null</exception>
    Task<int> EstimateOutputTokensAsync(TRequest request, CancellationToken cancellationToken = default);

    /// <summary>
    /// Estimates the total number of tokens (input + output) for the request.
    /// Default implementation sums EstimateInputTokensAsync and EstimateOutputTokensAsync,
    /// but implementations may override for efficiency or different logic.
    /// </summary>
    /// <param name="request">The request to estimate total tokens for</param>
    /// <param name="cancellationToken">Cancellation token for the operation</param>
    /// <returns>The estimated total number of tokens</returns>
    /// <exception cref="ArgumentNullException">Thrown when request is null</exception>
    async Task<int> EstimateTotalTokensAsync(TRequest request, CancellationToken cancellationToken = default)
    {
        var inputTokens = await EstimateInputTokensAsync(request, cancellationToken);
        var outputTokens = await EstimateOutputTokensAsync(request, cancellationToken);
        return inputTokens + outputTokens;
    }
}
