namespace TokenRateGate.Abstractions;

/// <summary>
/// Extracts actual token usage information from LLM provider responses.
/// This enables accurate tracking and efficiency measurement by comparing
/// actual usage against estimated tokens.
/// </summary>
/// <typeparam name="TResponse">The type of response object from the LLM provider</typeparam>
public interface ITokenUsageExtractor<in TResponse>
{
    /// <summary>
    /// Extracts the actual number of input tokens consumed by the request
    /// from the provider's response. Most providers include this in their
    /// response metadata.
    /// </summary>
    /// <param name="response">The response from the LLM provider</param>
    /// <returns>
    /// The actual number of input tokens consumed, or null if not available in the response
    /// </returns>
    /// <exception cref="ArgumentNullException">Thrown when response is null</exception>
    int? ExtractInputTokens(TResponse response);

    /// <summary>
    /// Extracts the actual number of output tokens generated by the LLM
    /// from the provider's response. Most providers include this in their
    /// response metadata.
    /// </summary>
    /// <param name="response">The response from the LLM provider</param>
    /// <returns>
    /// The actual number of output tokens generated, or null if not available in the response
    /// </returns>
    /// <exception cref="ArgumentNullException">Thrown when response is null</exception>
    int? ExtractOutputTokens(TResponse response);

    /// <summary>
    /// Extracts the total number of tokens (input + output) consumed by the request.
    /// Default implementation sums ExtractInputTokens and ExtractOutputTokens,
    /// but implementations may override if the provider supplies a total directly.
    /// </summary>
    /// <param name="response">The response from the LLM provider</param>
    /// <returns>
    /// The total number of tokens consumed, or null if not available in the response
    /// </returns>
    /// <exception cref="ArgumentNullException">Thrown when response is null</exception>
    int? ExtractTotalTokens(TResponse response)
    {
        var inputTokens = ExtractInputTokens(response);
        var outputTokens = ExtractOutputTokens(response);

        if (inputTokens.HasValue && outputTokens.HasValue)
        {
            return inputTokens.Value + outputTokens.Value;
        }

        return null;
    }
}
